name: Famed Scanners

on: push

jobs:
  send_contracts_to_slither:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v1
      - run: |
          shopt -s globstar; tar -zcvf archive.tar.gz **/*.sol
          curl -X POST {{ .Host}}/famed/repos/{{ .Owner}}/{{ .Repo}}/scanner -F "name=slither" -F files=@archive.tar.gz
  send_contracts_to_semgrep:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v1
      - run: |
          shopt -s globstar; tar --exclude='./.git' -zcvf archive.tar.gz ./
          curl -X POST {{ .Host}}/famed/repos/{{ .Owner}}/{{ .Repo}}/scanner -F "name=semgrep" -F files=@archive.tar.gz
